//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Septem.Utils.Domain.Mediatr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssueMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Septem.Utils.Domain.Mediatr.IssueMessages", typeof(IssueMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code already used. Repeat verification.
        /// </summary>
        public static string DraftAlreadyUsed {
            get {
                return ResourceManager.GetString("DraftAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} with key {1} already exists.
        /// </summary>
        public static string EntityAlreadyExists {
            get {
                return ResourceManager.GetString("EntityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} with key {1} not found.
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filter status.
        /// </summary>
        public static string FilterInvalidStatus {
            get {
                return ResourceManager.GetString("FilterInvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification not submited.
        /// </summary>
        public static string InvalidVerificationCodeStatus {
            get {
                return ResourceManager.GetString("InvalidVerificationCodeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code retries count exceeded.
        /// </summary>
        public static string MaxAttemptExceeded {
            get {
                return ResourceManager.GetString("MaxAttemptExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code timeout exceeded.
        /// </summary>
        public static string MaxLifetimeExceeded {
            get {
                return ResourceManager.GetString("MaxLifetimeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package can&apos;t apply to this filter.
        /// </summary>
        public static string PackageCategoryNotAllowed {
            get {
                return ResourceManager.GetString("PackageCategoryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package not active.
        /// </summary>
        public static string PackageNotActive {
            get {
                return ResourceManager.GetString("PackageNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can repeat in {0} seconds.
        /// </summary>
        public static string RepeatTimeLimit {
            get {
                return ResourceManager.GetString("RepeatTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change status of {0} from {1} to {2}.
        /// </summary>
        public static string TransitionStatusError {
            get {
                return ResourceManager.GetString("TransitionStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid balance.
        /// </summary>
        public static string UserBalanceError {
            get {
                return ResourceManager.GetString("UserBalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not active.
        /// </summary>
        public static string UserInvalidStatus {
            get {
                return ResourceManager.GetString("UserInvalidStatus", resourceCulture);
            }
        }
    }
}
